GET http://localhost:3000/get

###

GET http://localhost:3000/

###

GET http://localhost:3000/user/data
###
POST http://localhost:3000/user/add
Content-Type: application/json

{
    "username" : "operator",
    "password" : "root",
    "role"     : "ADMIN"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "glepero",
    "password" : "mek"
}

###

GET  http://localhost:3000/user/logout